
package co.za.fnb.volunteers.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Categories", targetNamespace = "http://www.example.org/Categories/", wsdlLocation = "file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/Categories.wsdl")
public class Categories
    extends Service
{

    private final static URL CATEGORIES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.za.fnb.volunteers.ws.Categories.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.za.fnb.volunteers.ws.Categories.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/Categories.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/Categories.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATEGORIES_WSDL_LOCATION = url;
    }

    public Categories(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Categories() {
        super(CATEGORIES_WSDL_LOCATION, new QName("http://www.example.org/Categories/", "Categories"));
    }

    /**
     * 
     * @return
     *     returns CategoriesPortType
     */
    @WebEndpoint(name = "CategoriesPort")
    public CategoriesPortType getCategoriesPort() {
        return super.getPort(new QName("http://www.example.org/Categories/", "CategoriesPort"), CategoriesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoriesPortType
     */
    @WebEndpoint(name = "CategoriesPort")
    public CategoriesPortType getCategoriesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Categories/", "CategoriesPort"), CategoriesPortType.class, features);
    }

}
