
package co.za.fnb.volunteers.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CategoriesPortType", targetNamespace = "http://www.example.org/Categories/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoriesPortType {


    /**
     * 
     * @param categoriesRequest
     * @return
     *     returns co.za.fnb.volunteers.ws.CategoriesResponseType
     */
    @WebMethod(action = "http://www.example.org/Categories/getCategories")
    @WebResult(name = "CategoriesResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCategories", targetNamespace = "http://www.example.org/Categories/", className = "co.za.fnb.volunteers.ws.GetCategories")
    @ResponseWrapper(localName = "getCategoriesResponse", targetNamespace = "http://www.example.org/Categories/", className = "co.za.fnb.volunteers.ws.GetCategoriesResponse")
    public CategoriesResponseType getCategories(
        @WebParam(name = "CategoriesRequest", targetNamespace = "")
        CategoriesRequestType categoriesRequest);

}
