
package co.za.fnb.volunteers.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DropOffPointsPortType", targetNamespace = "http://www.example.org/DropOffPoints/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DropOffPointsPortType {


    /**
     * 
     * @param dropOffPointsRequest
     * @return
     *     returns co.za.fnb.volunteers.ws.DropOffPointsResponseType
     */
    @WebMethod(action = "http://www.example.org/DropOffPoints/getDropOffPoints")
    @WebResult(name = "DropOffPointsResponse", targetNamespace = "")
    @RequestWrapper(localName = "getDropOffPoints", targetNamespace = "http://www.example.org/DropOffPoints/", className = "co.za.fnb.volunteers.ws.GetDropOffPoints")
    @ResponseWrapper(localName = "getDropOffPointsResponse", targetNamespace = "http://www.example.org/DropOffPoints/", className = "co.za.fnb.volunteers.ws.GetDropOffPointsResponse")
    public DropOffPointsResponseType getDropOffPoints(
        @WebParam(name = "DropOffPointsRequest", targetNamespace = "")
        DropOffPointsRequestType dropOffPointsRequest);

}
