
package co.za.fnb.volunteers.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DropOffPoints", targetNamespace = "http://www.example.org/DropOffPoints/", wsdlLocation = "file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/DropOffPoints.wsdl")
public class DropOffPoints
    extends Service
{

    private final static URL DROPOFFPOINTS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.za.fnb.volunteers.ws.DropOffPoints.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.za.fnb.volunteers.ws.DropOffPoints.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/DropOffPoints.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Kapeshi.Kongolo/VisualProjects/FNB_WIM_Volunteer_Practical/src/main/webapp/WEB-INF/wsdl/DropOffPoints.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DROPOFFPOINTS_WSDL_LOCATION = url;
    }

    public DropOffPoints(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DropOffPoints() {
        super(DROPOFFPOINTS_WSDL_LOCATION, new QName("http://www.example.org/DropOffPoints/", "DropOffPoints"));
    }

    /**
     * 
     * @return
     *     returns DropOffPointsPortType
     */
    @WebEndpoint(name = "DropOffPointsPort")
    public DropOffPointsPortType getDropOffPointsPort() {
        return super.getPort(new QName("http://www.example.org/DropOffPoints/", "DropOffPointsPort"), DropOffPointsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DropOffPointsPortType
     */
    @WebEndpoint(name = "DropOffPointsPort")
    public DropOffPointsPortType getDropOffPointsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DropOffPoints/", "DropOffPointsPort"), DropOffPointsPortType.class, features);
    }

}
